pipeline{
    agent{
        node{
            label 'AGENT-1'
        }
    }
    options{
        ansiColor('xterm')
    }
    stages{
        stage('init stage'){
            steps{
                script{
                    withAWS(region:'us-east-1',credentials:'aws_access') {
                        sh """
                            cd 10-sg
                            terraform init
                        """
                    }
                }
            }
        }
        stage('plan stage'){
            steps{
                script{
                    withAWS(region:'us-east-1',credentials:'aws_access') {
                        sh """
                            cd 10-sg
                            terraform plan
                        """
                    }
                }
            }
        }
        stage('deploy stage'){
            steps{
                script{
                    withAWS(region:'us-east-1',credentials:'aws_access') {
                        sh """
                            cd 10-sg
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
        
        stage('parallel trigger'){
            parallel {
                stage('SG rules'){
                    steps{
                        script{
                            build job: '30-sg-rules',
                            wait: false,
                            propagate: false
                        }
                    }
                }
                stage('trigger ecr'){
                    steps{
                        script{
                            build job: '40-ecr',
                            wait: false,
                            propagate: false  
                        }
                    }
                }
                stage('trigger acm'){
                    steps{
                        script{
                            build job: '70-acm',
                            wait: true,
                            propagate: true
                        }
                    }
                }
                stage('trigger eks'){
                    steps{
                        script{
                            build job: '90-eks',
                            wait: false,
                            propagate: false  
                        }
                    }
                }
            }
        }
    }
    
    post{
        always{
            echo 'I will always say Hello again!'
            cleanWs()
        }
        success {
            echo 'I will run if success'
        }
        failure {
            echo 'I will run if failure'
        }
        aborted {
            echo 'pipeline is aborted'
        }
    }
}