pipeline{
    agent{
        node{
            label 'AGENT-1'
        }
    }
    options{
        ansiColor('xterm')
    }
    stages{
        stage('init stage'){
            steps{
                script{
                    withAWS(region:'us-east-1',credentials:'aws_access') {
                        sh """
                            cd 10-sg
                            terraform init
                        """
                    }
                }
            }
        }
        stage('plan stage'){
            steps{
                script{
                    withAWS(region:'us-east-1',credentials:'aws_access') {
                        sh """
                            cd 10-sg
                            terraform plan
                        """
                    }
                }
            }
        }
        stage('deploy stage'){
            steps{
                script{
                    withAWS(region:'us-east-1',credentials:'aws_access') {
                        sh """
                            cd 10-sg
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
        stage('Trigger SG') {
            steps {
                script {
                    build job: '10-sg',
                        wait: false, // Wait for completion
                        propagate: false // Propagate status
                }
            }
        }
    }
    post{
        always{
            echo 'I will always say Hello again!'
            cleanWs()
        }
        success {
            echo 'I will run if success'
        }
        failure {
            echo 'I will run if failure'
        }
        aborted {
            echo 'pipeline is aborted'
        }
    }
}